# Generated by Django 4.0 on 2021-12-26 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10, verbose_name='Месяц')),
            ],
            options={
                'verbose_name': 'Месяц',
            },
        ),
        migrations.CreateModel(
            name='DataWeeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_created=True, verbose_name='Дата создания')),
                ('day', models.CharField(max_length=2, verbose_name='День месяца')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataweeks', to='week.month')),
            ],
            options={
                'verbose_name': 'Номер недели',
            },
        ),
    ]
