# Generated by Django 4.0 on 2021-12-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataweeks',
            options={'verbose_name': 'Дата', 'verbose_name_plural': 'Даты'},
        ),
        migrations.AlterModelOptions(
            name='month',
            options={'verbose_name': 'Месяц', 'verbose_name_plural': 'Месяца'},
        ),
        migrations.AddField(
            model_name='dataweeks',
            name='number_week',
            field=models.CharField(blank=True, max_length=10, verbose_name='Номер недели'),
        ),
    ]
