# Generated by Django 4.0 on 2021-12-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0002_alter_dataweeks_options_alter_month_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataweeks',
            name='number_week',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер недели'),
        ),
    ]
