# Generated by Django 4.0 on 2021-12-13 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.TextField(unique=True)),
                ('tg_first_name', models.TextField(blank=True)),
                ('tg_last_name', models.TextField(blank=True)),
                ('tg_username', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=11)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='TypeProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Вид процедуры',
                'verbose_name_plural': 'Виды процедур',
            },
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Вид товара',
                'verbose_name_plural': 'Виды товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('comment', models.TextField()),
                ('price', models.CharField(blank=True, max_length=15)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('typeproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typeproduct', to='arabot.typeproduct')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('comment', models.TextField()),
                ('price', models.CharField(blank=True, max_length=15)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('typeprocedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure', to='arabot.typeprocedure')),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедуры',
            },
        ),
    ]
