# Generated by Django 4.0 on 2021-12-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='procedure',
            field=models.ManyToManyField(blank=True, related_name='proceduries', to='arabot.Procedure'),
        ),
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='products', to='arabot.Product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tg_first_name',
            field=models.TextField(blank=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tg_id',
            field=models.TextField(unique=True, verbose_name='id телеграмм'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tg_last_name',
            field=models.TextField(blank=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tg_username',
            field=models.TextField(blank=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='comment',
            field=models.TextField(verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='price',
            field=models.CharField(blank=True, max_length=15, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.TextField(verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=15, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='typeprocedure',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='typeprocedure',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='typeproduct',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='typeproduct',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
    ]
